version: '3'

services:

  zenko:
    image: zenko/cloudserver:8.2.7
    ports:
      - 8000:8000
    environment:
      - SCALITY_ACCESS_KEY_ID=test-key
      - SCALITY_SECRET_ACCESS_KEY=test-secret
      - S3BACKEND=mem
      - ENDPOINT=zenko

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.25.0
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.33.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one

  hazelcast:
    image: hazelcast/hazelcast:4.1.5
    ports:
      - 5701:5701
      - 8088:8080

  arangodb:
    image: arangodb:3.7.11
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=100m

  inner-friends-user-profile-picture:
    image: damdamdeo/inner-friends-user-profile-picture
    ports:
      - 8080:8080
    environment:
      - quarkus.s3.endpoint-override=http://zenko:8000
      - quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://otel-collector:55680
      - quarkus.hazelcast-client.cluster-name=dev
      - quarkus.hazelcast-client.cluster-members=hazelcast:5701
      - arangodb.host=arangodb
      - arangodb.port=8529
      - arangodb.user=root
      - arangodb.password=password
      - arangodb.dbName=friends
    depends_on:
      - zenko
      - jaeger-all-in-one
      - otel-collector
      - hazelcast
      - arangodb
    restart: unless-stopped